PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX re:  <http://cplentinger.github.io/ontology-for-real-estate/operational-ontology/real-estate-listing.rdf#>
PREFIX gufo: <http://purl.org/nemo/gufo#>

SELECT ?listing ?roomCountValue
WHERE {
    ?listing rdf:type re:RealEstateListing .

    ?product rdf:type re:RealEstateProduct ;
        gufo:isComponentOf ?listing .

    ?structure rdf:type re:Structure ;
        gufo:isComponentOf ?product .

    ?roomCount rdf:type re:RoomCount ;
        gufo:mediates ?structure ;
        re:roomCount ?roomCountValue .

    ?bedroomType rdf:type re:Bedroom ;
        gufo:inheresIn ?roomCount .
}
