PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX re:  <http://cplentinger.github.io/ontology-for-real-estate/operational-ontology/real-estate-listing.rdf#>
PREFIX gufo: <http://purl.org/nemo/gufo#>

SELECT ?listing ?featureNameValue
WHERE {
    ?listing rdf:type re:RealEstateListing .

    ?product rdf:type re:RealEstateProduct ;
        gufo:isComponentOf ?listing .

    VALUES ?featureType {
        re:AirConditioning
        re:RealEstateFeature
    }

    ?feature gufo:isComponentOf ?product ;
        rdf:type ?featureType .

    ?featureName rdf:type re:FeatureName ;
        gufo:inheresIn ?feature ;
        gufo:hasQualityValue ?featureNameValue .

    FILTER (
        ?featureType = re:AirConditioning ||
        (
            ?featureType = re:RealEstateFeature &&
            regex(?featureNameValue, "\\b(a\\/?c|air[\\s-]?con(dition(ing)?)?)\\b", "i")
        )
    )
}